apiVersion: apps/v1
kind: Deployment
metadata:
  name: jobs
  namespace: development
  labels:
    app: jobs
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 50%
      maxSurge: 50%
  selector:
    matchLabels:
      app: jobs
  template:
    metadata:
      namespace: development
      labels:
        app: jobs
    spec:
      containers:
      - name: jobs
        image: cr.yandex/crpfb8t478v3of681kce/jobs:$CIRCLE_SHA1
        imagePullPolicy: Always
        readinessProbe:
          exec:
            command:
            - cat
            - /tmp/.healthy
          initialDelaySeconds: 5
          periodSeconds: 5
        envFrom:
          - configMapRef:
              name: jobs-config
      imagePullSecrets:
      - name: gitlabregistrycred
